### ISSUE TITLE
The "image" namespace is not available

### ISSUE THREAD

**Issue by abeiderman** [rick/linode#30]
The image namespace is not loaded into the Linode class. This causes a no method error whenever trying to use the image API.  The workaround at the moment is to monkey patch Linode and call "has_namespace :image".

**Comment by abeiderman** [comment]
There is an open pull request (https://github.com/rick/linode/pull/27) by @displague that addresses this issue.

**Comment by rick** [comment]
#27 has been merged. Sorry for the prolonged delay(s). 

Actively seeking a maintainer with the time to keep up with the project.
