### ISSUE TITLE
Open SSL Error

### ISSUE THREAD

**Issue by danielhickman** [rick/linode#31]
This gem doesn't require a SSL certificate does it? This error means nothing to me, and a Google search only suggested using a workaround certificate for a different looking issue (which I tried for kicks and giggles, then removed).

**Error:**
```
D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from D:/Program Files/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.7/lib/httparty.rb:492:in `post'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/httparty-0.13.7/lib/httparty.rb:587:in `post'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/linode-0.9.0/lib/linode.rb:96:in `post'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/linode-0.9.0/lib/linode.rb:81:in `send_request'
        from D:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/linode-0.9.0/lib/linode.rb:15:in `block (2 levels) in has_method'
        from linode.rb:6:in `<main>'
```

**Code:**
```ruby
require 'rubygems'
require 'linode'

api_key = "My API Key that I am not gonna put in here"
l = Linode.new(:api_key => api_key)
puts l.test.echo(:foo => 'bar', :baz => 'xyzzy')
```

Windows 10, Ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32], Gem 2.5.1, Linode 0.9.0

**Comment by displague** [comment]
Linode disabled SSLv3 awhile ago.

Can you try changing: https://github.com/rick/linode/blob/master/lib/linode.rb#L96 to
```
HTTParty.post(api_url, :body => data, :ssl_version => :TLSv1).parsed_response
```

This feels ultimately like something wrong upstream or in the Windows configuration or behavior.

**Comment by danielhickman** [comment]
I replaced that line and received the same exact error including the line numbers.

**Comment by SirCmpwn** [comment]
Can you try simply opening [this link](https://api.linode.com/) in IE (yes, IE) and see what happens? If you get an SSL error, then your system is misconfigured. If you get `{"ERRORARRAY":[{"ERRORCODE":4,"ERRORMESSAGE":"Authentication failed"}],"DATA":{},"ACTION":""}`, then we have more to look into.

**Comment by danielhickman** [comment]
@SirCmpwn IE opens (in a text editor) or saves the JSON file. If I change my default program for JSON files to IE and then hit open, it tries to open it in the download manager.

Edge and Chrome both show the connection is encrypted and trusted.

**Comment by SirCmpwn** [comment]
Interesting. That makes me less sure that it's an issue with your system configuration. I don't think I'll be able to provide further assistance until I can get my hands on a Windows machine to reproduce with.

**Comment by erkie** [comment]
Getting the same on mac.

```SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/erik/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.5/lib/httparty.rb:476:in `post'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.5/lib/httparty.rb:564:in `post'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/linode-0.9.0/lib/linode.rb:96:in `post'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/linode-0.9.0/lib/linode.rb:81:in `send_request'
	from /Users/erik/.rvm/gems/ruby-2.2.1/gems/linode-0.9.0/lib/linode.rb:15:in `block (2 levels) in has_method'
	from bin/start-spark-cluster.rb:3:in `<main>'```

Just ran `gem install linode` today so it should be latest version.

**Comment by erkie** [comment]
[Seems to be a common error with RVM installations.](http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat) fix is client side and not an gem error

**Comment by displague** [comment]
@danielhickman does @erike's fix work for you?

**Comment by danielhickman** [comment]
I don't have RVM. It seems it's not for Windows. Is RVM a requirement?

**Comment by erkie** [comment]
@danielhickman the linked stackoverflow thread has a lot of different instances of the same error. This was one I found for windows. Try following these steps: http://stackoverflow.com/a/35429863/224732

**Comment by danielhickman** [comment]
I tried that one before and a tried it again too.

**The only ones that worked were:**
Adding this to remove SSL (very bad idea)
```
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

Installing https://github.com/stevegraham/certified and adding (This method feels kinda hacky)
```
require 'certified'
```
