### ISSUE TITLE
Gem version 0.9.1

### ISSUE THREAD

**Issue by moxley** [rick/linode#38]
Hi, issue #32 is breaking our Chef infrastructure. Would you mind releasing a new version of the gem for 0.9.1? In the meantime, we'll set an explicit Git SHA in our Gemfile. It'll be a bit messy. Thanks!

**Comment by displague** [comment]
I just pushed [v0.9.1](https://github.com/rick/linode/releases/tag/v0.9.1).

Let me know if this works for you.

**Comment by moxley** [comment]
It works beautifully. Thank you!
